name: olamaslik
favicon: null
layout_spectrum: 0.6021335027180612
typography_spectrum: 0.7010462994221598
title: ola maslik
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#231e1b'
    - '#7a6e60'
    - '#b0becb'
    - '#908a7c'
  brandStrength: 0.1875
  lightness: 0.6073468590620905
  saturation: 0.5
  rhythmicContrast: 0.5614949162118137
purpose: []
