title: ola maslik
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.5
  brandStrength: 0.5168634
  lightness: 0.6073468590620905
  brandColors:
    - '#201E1F'
    - '#413A3A'
    - '#F2F1FC'
    - '#7F5E37'
    - '#6F90D8'
  rhythmicContrast: 0.5614949162118137
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: olamaslik
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.9865093
layout_spectrum: 0.4494098
